# This file was generated by GoReleaser. DO NOT EDIT.
cask "claude-switch" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "cc77522e6b050306346a6007540eed3af4014980fe8200c9ec22c6c7cbbd2d3c"
      url "https://github.com/hleidev/claude-switch/releases/download/v#{version}/claude-switch_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e85a198efc151c62079fe4334fd724441bc9a5f4124974629ae98bd498372e0a"
      url "https://github.com/hleidev/claude-switch/releases/download/v#{version}/claude-switch_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0038a91419128701d006839012dfd621fb9d783393fbde6d41087c989770d754"
      url "https://github.com/hleidev/claude-switch/releases/download/v#{version}/claude-switch_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "991e2b51af94f7bc1d705a1b5458cc4ca209d1c5a90ba487ed0185bdab2dfc17"
      url "https://github.com/hleidev/claude-switch/releases/download/v#{version}/claude-switch_#{version}_linux_arm64.tar.gz"
    end
  end

  name "claude-switch"
  desc "Switch Claude Code's backend per terminal — one command, no global config"
  homepage "https://github.com/hleidev/claude-switch"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claude-switch"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/claude-switch"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    `cs` is a shell function, not a binary — two more steps are required,
    otherwise `cs` will report "command not found":

      1. claude-switch setup   # writes the integration into your rc file
      2. exec $SHELL           # or just open a new terminal

    Step 1 is idempotent. Run `claude-switch doctor` if `cs` still is not found.
  EOS
end
