# This file was generated by GoReleaser. DO NOT EDIT.
cask "claude-switch" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "c27e21ef66405a71ab06597e449a5b40058b4706942e9115b115699e3dddb538"
      url "https://github.com/hleidev/claude-switch/releases/download/v#{version}/claude-switch_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "237cadd533ae7aafd22008e63a579f041b45a7a5d6e119db109f3e3dec5c848e"
      url "https://github.com/hleidev/claude-switch/releases/download/v#{version}/claude-switch_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c6f93294da0388bccdc6844ca04887f382e1048a6a5a7062447ab0365cc2ed24"
      url "https://github.com/hleidev/claude-switch/releases/download/v#{version}/claude-switch_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f6496956c380d954435a1f8a0d98f12bea79b6156bbf76f91963624c1310b0ab"
      url "https://github.com/hleidev/claude-switch/releases/download/v#{version}/claude-switch_#{version}_linux_arm64.tar.gz"
    end
  end

  name "claude-switch"
  desc "Switch Claude Code's backend per terminal — one command, no global config"
  homepage "https://github.com/hleidev/claude-switch"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cs"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cs"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    One more step — `cs use` needs shell integration to change the current
    terminal's environment:

      1. cs setup      # writes the integration into your rc file
      2. exec $SHELL   # or just open a new terminal

    Step 1 is idempotent. Run `cs doctor` if anything looks off.
  EOS
end
