# This file was generated by GoReleaser. DO NOT EDIT.
cask "claude-switch" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "77452014047e7e8fefce924827a7f491f6419d0a8bb68667316647966cb7c751"
      url "https://github.com/hleidev/claude-switch/releases/download/v#{version}/claude-switch_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "99c0ac4873b29014637724b7a9634f46960549b2d14ed48ff7b4e4be49206528"
      url "https://github.com/hleidev/claude-switch/releases/download/v#{version}/claude-switch_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a34b1d3b7861b0ffb725afb86c1a52907b6f4586252e7960bb1bfbd49569b7ee"
      url "https://github.com/hleidev/claude-switch/releases/download/v#{version}/claude-switch_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2c774137bf3b6733985b9cff2a815bc30ad4d214e0c8042ebaa48d44bf56a6eb"
      url "https://github.com/hleidev/claude-switch/releases/download/v#{version}/claude-switch_#{version}_linux_arm64.tar.gz"
    end
  end

  name "claude-switch"
  desc "Switch Claude Code's backend per terminal — one command, no global config"
  homepage "https://github.com/hleidev/claude-switch"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claude-switch"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/claude-switch"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    `cs` is a shell function, not a binary — two more steps are required,
    otherwise `cs` will report "command not found":

      1. claude-switch setup   # writes the integration into your rc file
      2. exec $SHELL           # or just open a new terminal

    Step 1 is idempotent. Run `claude-switch doctor` if `cs` still is not found.
  EOS
end
